---

name: dendro
channels:
  - conda-forge
dependencies:
  - python==3.13
  - numpy
  - scipy
  - pytorch
  - heat
  - matplotlib
  - jupyter
  - jupytext
  - pytest
  - coverage
  - black
  - ruff

  - pip
  - pip:
    - astrodendro
